### ISSUE TITLE
Add visual cues whever the backoffice waits for kuzzle to answer

### ISSUE THREAD

**Issue by gggeek** [kuzzleio/kuzzle-admin-console#323]
I am not sure about the number of places where this is needed.

However it is quite visible in the 'out of the box experience', as when connecting the BO to a brand new Kuzzle the first thing that happens is that a big 'kuzzle' writing appears in a square on white background, and stays on screen for at least a couple of seconds, without the user getting any visible feedback that something goes on under the hood.

**Comment by gggeek** [comment]
ex: in ye olde times, the cursor changeth to an hourglass whenever the app was doing background stuff...

**Comment by xbill82** [comment]
Added loaders pretty much everywhere in v4 :)
