### ISSUE TITLE
Backoffice goes back to page 1 all the time

### ISSUE THREAD

**Issue by BaptisteKaliop** [kuzzleio/kuzzle-admin-console#344]
When editing and saving a document page X, I would like to be sent back to page X  when i'm redirect to the list of documents

That's disturbing to go page 3, edit, sent back to page 1, go back to page 3 etc...

**Comment by ballinette** [comment]
the issue is not about the page itself, but about the whole filters and sorting rules.
That means, to answer to this demand, we need to keep the context of the listing before showing the document.
To be discussed in a UX conception workshop.

**Comment by xbill82** [comment]
The whole filters system has been rethought and now the pagination is remembered across actions
