### ISSUE TITLE
Broken dropdown if collection contains underscore

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle-admin-console#350]
As @roukien states on Gitter, the dropdown menu for a collection does not show if the name of the collection contains an underscore. This seems to be due to an ID-parsing rule in Materialize CSS.

**Comment by Aschen** [comment]
We need to investigate Materialize to definitively fix this issue.  
For now we have only made a quick fix for collection names with underscore

**Comment by xbill82** [comment]
Closing as not reproducing anymore
