### ISSUE TITLE
Update credentials with multiple strategies

### ISSUE THREAD

**Issue by Tyki** [kuzzleio/kuzzle-admin-console#364]
When I try to update the credentials of a specific strategy, the backoffice show me the error of another strategy.

It looks like the backoffice call the "update" function of all the strategies registered

Use case : 
Updating the password of an user using "local" strategy
I have another strategy named facebook in which I have the function "update" that directly throw an error

The backoffice tells me this : 

Facebook authentication strategy: unsupported method

The thing is, the credentials is still updated for local strategy.

**Comment by ballinette** [comment]
actually, `updateCredentials` is called for each registered strategy each time we edit a user, event if we do not change any credentials...
I guess we should save user info and credentials for each strategy indepedently.
