### ISSUE TITLE
Browsing document doesn't show explicit scroll area

### ISSUE THREAD

**Issue by ScreamZ** [kuzzleio/kuzzle-admin-console#401]
Hey,

I'm searching for a user using the security's query interface.

Once I found mine, I was surprised to see that no all fields were displayed.
After some time I figured out that you can scroll on the object… (You can shame me, but if I missed, I should not be alone :D)

I think a little improvement could be to display the scroll bar on the right side. This could improve accessibility on the back-office and make him even more pleasant to use :)

Regards

**Comment by Aschen** [comment]
Hello,

I'm not sure to understand what you mean, I can see the scroll bar

![image](https://user-images.githubusercontent.com/4447392/40775717-09299430-64c9-11e8-81b9-a2c3f555f871.png)

Can you be more explicit or provide a screenshot please ?
