### ISSUE TITLE
Sometimes it's impossible to scroll

### ISSUE THREAD

**Issue by Tyki** [kuzzleio/kuzzle-admin-console#408]
On the first loading of the backoffice, **_randomly_** it's impossible to scroll with a lot of indexes

## Expected Behavior

Be able to scroll

## Current Behavior

Impossible to scroll

## Possible Solution

Do a F5 and pray that the console is correctly initialized

## Steps to Reproduce

1. Create some indexes : `for i in {1..40}; do; curl -H "Content-Type: application/json" -X POST  "http://localhost:7512/test$i/_create"; sleep 0.1; done`
2. Login as anonymous to the admin console

## Context (Environment)

Using http://kuzzle-backoffice.netlify.com/#/data

On the first loading, the scrollbar is missing, making it impossible to scroll
![image](https://user-images.githubusercontent.com/2605688/40770167-31a753ca-64ba-11e8-9bed-350edf29cec4.png)

After a clear-cache & reload, the scrollbar is there
![image](https://user-images.githubusercontent.com/2605688/40770194-4287e9c0-64ba-11e8-9f34-9c9db73661ec.png)

**Comment by Njuelle** [comment]
Hi!
I can't reproduce this bug on chrome and firefox.
After you cleared the cache, are you able to reproduce this bug?
If so, what are the steps to reproduce?

Thx

**Comment by Tyki** [comment]
Well @Aschen was able to reproduce the issue when i wrote this ticket

Sometimes, I still have this issue. Not sure how to reproduce

**Comment by Aschen** [comment]
I will show you @Njuelle
