### ISSUE TITLE
[Improvement] Display query from graphic interface to json interface

### ISSUE THREAD

**Issue by HamHamFonFon** [kuzzleio/kuzzle-admin-console#410]
## Expected Behavior
When i build a search query with the graphic interface, having the query build in JSON at same time (after submit, not necessary in real-time) would be a good add-on. For a beginner in Elastic Search (like me ^^), sometimes it's difficult to build a correct query with all "should", "must", "bool" etc...

## Possible Solution
I think it's a good support to on left-side the query helper, and on the right-side the result of the query builded.

**Comment by etrousset** [comment]
https://jira.kaliop.net/browse/KZL-120

**Comment by jenow** [comment]
Merged on https://github.com/kuzzleio/kuzzle-admin-console/pull/516
