### ISSUE TITLE
kuzzle-backoffice does not  create admin on kuzzle cluster

### ISSUE THREAD

**Issue by plavacquery** [kuzzleio/kuzzle-admin-console#412]
## Expected Behavior
After creating cluster kuzzle, we launch kuzzle-backoffice. kuzzle-backoffice connect to cluster and propose to create admin user

## Current Behavior
After creating cluster kuzzle, we launch kuzzle-backoffice. kuzzle-backoffice fails to connect ad do not allow to create admin user. we use local kuzzle-backoffice v2.1.3 for creating admin.

After creating admin, we switch to kuzzle-backoffice (last version) and it 's working fine

## Steps to Reproduce
1. Install cluster kuzzle
2. start kuzzle 'http://kuzzle-backoffice.netlify.com'
3. Kuzzle backoffice could not create admin user 

## Context (Environment)
cluster-kuzzle --> (last version)
kuzzle-backoffice ---> (last version) "http://kuzzle-backoffice.netlify.com/#/data"
Linux

**Comment by Aschen** [comment]
Hi @plavacquery,

I just tried to reproduce your issue but I was able to create the first admin with the admin console (backoffice).  
Did you try with the latest version of the admin console ? http://console.kuzzle.io

**Comment by plavacquery** [comment]
Hi @Aschen 

It's working fine with the last version of admin console :)
