### ISSUE TITLE
Add validation to the Basic Filter form

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle-admin-console#433]
## Expected Behavior
When filling the Basic Filter form, we should not be able to insert invalid values (like, for example, empty fields). When we hit the SEARCH button, we should see an error and the malformed field highlighted in red.

## Current Behavior
Currently, the form allows to send invalid queries.

## Possible Solution
Add a form validation mechanism.

## Steps to Reproduce
* Select BasicFilter mode
* Type something only in the Attribute field
* Submit the form
* You should see an error and the component is re-render so it switch on the QuickFilter mode

**Comment by Aschen** [comment]
Fixed here: https://github.com/kuzzleio/kuzzle-admin-console/pull/432/files#diff-6e091e942f6092803fe8f246a3c9b6abR113
