### ISSUE TITLE
404 error when clicking on a collection name in the sidebar search

### ISSUE THREAD

**Issue by lethak** [kuzzleio/kuzzle-admin-console#437]
## Expected Behavior
The dedicated collection page should open instead of a 404 error.

## Current Behavior
404 error when clicking on a collection name in the sidebar search

![screenshot-console kuzzle io-2018 08 23-11-25-15](https://user-images.githubusercontent.com/1705300/44517366-c9414200-a6c7-11e8-8a82-e5e728f1616b.png)

generated url: http://console.kuzzle.io/#/data/global/%3Cstrong%20class=%22highlight%22%3Eapplications%3C%2Fstrong%3E

correct url:
http://console.kuzzle.io/#/data/global/applications

## Steps to Reproduce
1. Open the admin console
2. Search for an existing collection name in the left sidebar
3. click on the found collection name under the index name (called "applications" in the previous screenshot)

## Context (Environment)
http://console.kuzzle.io

**Comment by xbill82** [comment]
Can't reproduce this. Whenever I open an index I can properly see the collections stored inside.

**Comment by xbill82** [comment]
Ok, now I can reproduce.
