### ISSUE TITLE
Unable to click "use SSL" in the connection creation page

### ISSUE THREAD

**Issue by lethak** [kuzzleio/kuzzle-admin-console#438]
## Expected Behavior
I should be able to click "use SSL" in the connection creation page

![screenshot-console kuzzle io-2018 08 23-11-37-31](https://user-images.githubusercontent.com/1705300/44517860-0b1eb800-a6c9-11e8-8c0b-af3ea164fb4a.png)

## Current Behavior
Nothing happens upon clicking "use SSL"

## Temp workarround
saving without "use SSL" and editing the boolean value in the localStorage configuration do work.

## Steps to Reproduce
1. open the console
2. create a new connection
3. click "use SSL"

## Context (Environment)
* http://console.kuzzle.io and https://console.kuzzle.io
* Google chrome
* Firefox

**Comment by xbill82** [comment]
Can't reproduce this. When I click on the "use SSL" it gets properly checked.

**Comment by lethak** [comment]
It was fixed last week in 2.2.0 https://github.com/kuzzleio/kuzzle-admin-console/releases/tag/2.2.0
