### ISSUE TITLE
Add capability to delete all documents

### ISSUE THREAD

**Issue by ScreamZ** [kuzzleio/kuzzle-admin-console#460]
# Add Capability to delete all documents of a matching query

Currently we are only deleting documents within the the current page.

Could be nice if we could delete every documents matching the query. Maybe add a button `Delete all matching query`.

![Issue description](https://media.giphy.com/media/YlmNLW8srQgBueuUnw/giphy.gif "Issue description")

Regards

**Comment by Aschen** [comment]
Yes it would be nice to be able to perform action on all documents matching the query and not the current page only.

Internal task: https://jira.kaliop.net/browse/KZL-603
