### ISSUE TITLE
Add Capability to switch to raw JSON without losing the query

### ISSUE THREAD

**Issue by ScreamZ** [kuzzleio/kuzzle-admin-console#461]
# Add Capability to switch to raw JSON without losing the query

Currently when you switch to RAWJson you're losing the query you're building. Could be nice to switch without losing.

![Feature description](https://media.giphy.com/media/lL2fLqLO9e8H0862yB/giphy.gif "Feature description")

Regards

**Comment by Aschen** [comment]
I think it's a very nice feature to have. It could help developer who are not familiar with Elasticsearch to learn the syntax.

What do you think @kuzzleio/core ?

**Comment by jenow** [comment]
Added in https://github.com/kuzzleio/kuzzle-admin-console/pull/516
