### ISSUE TITLE
e.refreshSearch is not a function

### ISSUE THREAD

**Issue by Tyki** [kuzzleio/kuzzle-admin-console#463]
After a fresh installation of Kuzzle 1.5 and using console.kuzzle.io (2.2.2), after deleting an user, I have an error : e.refreshSearch is not a function

Step to reproduce : 

Create a kuzzle user using API (my use case)
Go to console.kuzzle.io
Find the fresh new user
Delete using the trash icon
Constat the error

**Comment by Tyki** [comment]
I have Chrome 69 on a Macbook

**Comment by Aschen** [comment]
Ok I reproduce it:
  - Install SDK JS 6: 
  - Create user with this script: https://gist.github.com/Aschen/659c8bd8dcea8bfc43cde7290ee96b6e
  - Open admin console -> Security tab
  - Select newly created user and user the `DELETE` button

**Comment by Tyki** [comment]
@Aschen issue is back with console 2.2.3

**Comment by jenow** [comment]
I cannot reproduce in 2.2.9, can you tell me if you still have the problem and close this issue otherwise? Thanks :)
