### ISSUE TITLE
Allow to use gte / lte and other like filter in search

### ISSUE THREAD

**Issue by ScreamZ** [kuzzleio/kuzzle-admin-console#466]
# Add capability to filter with greater / lower than.

In kuzzle admin console, it could be nice to have « math » operators for the search panel: 

<a href="https://ibb.co/csCb69"><img src="https://preview.ibb.co/jLiSDp/Screenshot_2018_10_10_at_16_23_54.png" alt="Screenshot_2018_10_10_at_16_23_54" border="0"></a>

Currently there is only `match` and `equals`.

Best regards

**Comment by jenow** [comment]
Added in https://github.com/kuzzleio/kuzzle-admin-console/pull/515
