### ISSUE TITLE
Playing the same advanced query doesn't update the result set

### ISSUE THREAD

**Issue by ScreamZ** [kuzzleio/kuzzle-admin-console#467]
I'm in the admin console I'm running the following query : 

```json 
{
  "query": {
    "prefix": {
      "image.uri": "https://res.cloudinary.com/dkiv4hwn3/image/upload/v"
    }
  }
}
```

## Expected Behavior

I click on `Search` and I get a result set indicating X documents.
I run a script in another place that is supposed to the reduce this set matching this query.
I click again,  same amount of documents matching displayed at the bottom of the page.
I reload the page, this replay the query and the correct amount is displayed.

## Possible Solution
The query is probably not sent.

## Context (Environment)

I'm using **admin console 2.2.2**

Best regards

**Comment by etrousset** [comment]
The issue has been reproduced and triggered: https://jira.kaliop.net/browse/KZL-694
Thanks for the feedback

**Comment by jenow** [comment]
This has been fixed in this release https://github.com/kuzzleio/kuzzle-admin-console/releases/tag/2.2.5
