### ISSUE TITLE
Strange behaviour when editing a host configuration

### ISSUE THREAD

**Issue by Tyki** [kuzzleio/kuzzle-admin-console#469]
When I try to edit the "host" field inside a connection configuration, the field force to edit by the end of the field.

I have to delete the whole string to modify the beginning.

## Steps to Reproduce

1. Create a new connection in the console with a host like "my-host.com"
2. Edit the new connection and try to modify the "my" for "the", the input field force to edit at the end 
3.
4.

## Context (Environment)

Console Kuzzle 2.2.2

**Comment by xbill82** [comment]
Yes, it's weird! When you focus the field by clicking on it, the text of its value will be selected, which will make the cursor go to the end of the text. You can then move the cursor using the arrows but you can't actually _click_ anywhere in the text field to place the cursor where you want. This is a bug. Thanks!

**Comment by jenow** [comment]
This has been fixed by updating Materialize-css to version 1.0.0.
For now it's available on next-console.kuzzle.io.
I will close this issue once we merge the development branch to master.

**Comment by jenow** [comment]
Dev has been merged on master
