### ISSUE TITLE
No feedback on ES error when trying to update existing user mapping

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle-admin-console#485]
Go to Security -> Users, having existing users with content fields and an existing mapping. Go to the "Edit Mapping" page. Change the type of an existing property (this is an illegal operation in Elasticsearch). Click "Update".

## Expected Behavior
An error should be shown saying it's not possible to change the type of an existing property. Only adding new properties is allowed.

## Current Behavior
Nothing is shown. We are redirected to the document list page as if everything went fine.

## Possible Solution
Show the damn error.

## Context (Environment)
Admin console 2.2.3

**Comment by jenow** [comment]
An error is shown in the version 2.2.9:

![a](https://user-images.githubusercontent.com/592088/54609126-98a16b00-4a52-11e9-97b1-4a28f8cf1195.png)

Do you still have the problem or can I close this issue?
