### ISSUE TITLE
Updating a document changes its author

### ISSUE THREAD

**Issue by thenikso** [kuzzleio/kuzzle-admin-console#495]
When updating a document as an administartor, the `_kuzzle_info.author` is changed to the user editing the document (aka the administrator itself).

This may, for example, break custom policy plugins checking for the `_kuzzle_info.author`.

## Expected Behavior
The `_kuzzle_info.author` is maintained to the original author of the document.

## Current Behavior
The `author` is changed along with the `updated` (the `updated` is expected to change).

## Possible Solution
In https://github.com/kuzzleio/kuzzle-admin-console/blob/master/src/components/Data/Documents/Update.vue a `replaceDocumentPromise` is used and perhaps there should be an option to maintain the `author` as specified?

This would also allow to attribute a document to a specific author which might come in handy.

Alternatively the documentation might suggest not to treat the `_kuzzle_info.author` field for application logic but instead add a similar filed to the custom app data.

## Steps to Reproduce
1. Create a document with a user FOO
2. Login in the admin console with the user BAR
3. Update the document created by FOO as the user BAR
4. The document appears now as authored by BAR instead of FOO

## Context (Environment)
I discover this behavior when using the admin console to change a user document and the user could no longer see the document because the custom policy plugin was checking for `_kuzzle_info.author === request.context.user._id`.

Trying to set the `author` back to its original value from the admin console (as an admin) did not work as it was automatically reset to the admin user itself.

**Comment by xbill82** [comment]
Hey @thenikso thanks a lot for the heads up. I've been able to reproduce the bug. Going to treat it as soon as possible!

**Comment by etrousset** [comment]
@xbill82 is this bug related to admin console, or is it a misbehavior of Kuzzle?
I think meta data can be changed by clients, only Kuzzle Core can update them...

**Comment by xbill82** [comment]
@etrousset it's related to the Admin Console.
