### ISSUE TITLE
Admin console stuck in infinite loading even though Kuzzle is reachable

### ISSUE THREAD

**Issue by broken-bytes** [kuzzleio/kuzzle-admin-console#496]
## Expected Behavior
The Console should connect to Kuzzle instance at port 7512

## Current Behavior
The console gets stuck at the "Loading Kuzzle Admin Console" Screen.

## Possible Solution
None yet.

## Steps to Reproduce
1. Install Kuzzle via `sudo bash -c "$(curl http://get.kuzzle.io/)"`
2. Verify Kuzzle is running. For example run curl "localhost:7512/_now?pretty"
3. Download Admin console and place it in a web root folder.
4. Configure your WebServer to either direct a port or subdomain to the folder you placed the console in.
5. Access the console via the domain you configured your WebServer to use

## Context (Environment)
- NGINX 1.10.3
- Debian 9
- Current Kuzzle Version

Web Server config : 
```
server
{
  listen 80;
  server_name baas.***;
  return 301 https://$server_name$request_uri;
}
server {
   listen 443;
   server_name baas.***;

   index index.html index.htm index.php;
   ssl on;
   ssl_certificate ***********************;
   ssl_certificate_key *******************;

   root *************;
}

```

**Comment by jenow** [comment]
Have you tried to access it without SSL?
Also you don't have to put an http server, the admin console can be built with
```
npm run build
```
then accessible statically in your browser like this `file:///path/to/admin-console/dist/index.html`

**Comment by broken-bytes** [comment]
Yes I did that but it doesn't work.

**Comment by xbill82** [comment]
Hey @broken-bytes thanks for your heads up. Do you see any weird output on the console? Which browser are you using?

**Comment by xbill82** [comment]
We fixed a lot of things in the connection process of the v4
