### ISSUE TITLE
UI issue on mapping

### ISSUE THREAD

**Issue by ScreamZ** [kuzzleio/kuzzle-admin-console#540]
Hello,

![Screenshot 2019-06-14 at 11 08 38](https://user-images.githubusercontent.com/6640835/59498042-e7657200-8e94-11e9-85fb-ad2176ec3244.png)

I think it breaks.

I just created a collection and activated the form mode

**Comment by Aschen** [comment]
Hi @ScreamZ !
Thanks you for your feedback :) 
Can you provide the associated collection mapping ?

**Comment by ScreamZ** [comment]
@Aschen see #541

**Comment by jenow** [comment]
I cannot reproduce, can you tell me which browser/version and OS are you using?

**Comment by ScreamZ** [comment]
Brave - Version 0.65.121 Chromium: 75.0.3770.100 (Official Build) (64-bit)

No more issue, dunno why
