### ISSUE TITLE
Selecting Auto generate kuid for user blocks the user creation at the next step

### ISSUE THREAD

**Issue by barroudjo** [kuzzleio/kuzzle-admin-console#545]
![image](https://user-images.githubusercontent.com/7458434/59969008-20ac7a80-9544-11e9-94df-d8db58450c02.png)

## Expected Behavior
User should be created with an auto generated kuid

## Current Behavior
Error message when clicking on save

## Steps to Reproduce
Issue noticed on Kuzzle 1.8.1 and console.kuzzle.io

## Context (Environment)

Kuzzle version: 1.8.1
Node.js version: 11.10.0
Admin Console Version: console.kuzzle.io, so latest ?

**Comment by xbill82** [comment]
Fixed in v4
