### ISSUE TITLE
Error when creating an user with autogenerated kuid

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle-admin-console#553]
## Expected Behavior

When creating an user, if you check the `Auto-generate` checkbox for the kuid, Kuzzle should generate a kuid for you.

## Current Behavior

The request did not execute
![image](https://user-images.githubusercontent.com/4447392/60347947-d05b6f80-99be-11e9-8b9f-d70df2030c96.png)

## Steps to Reproduce

1. Create an user and check `Auto-generate`
2. Go to the final step

## Context (Environment)
Kuzzle version: all
Admin Console Version: console.kuzzle.io

**Comment by jenow** [comment]
ref: https://github.com/kuzzleio/sdk-javascript/pull/408
