### ISSUE TITLE
Feature Request: increase size of left panel

### ISSUE THREAD

**Issue by BenjaminVadant** [kuzzleio/kuzzle-admin-console#554]
Hi,

it would be nice to have a slightly bigger left panel (or have it customizable). Because as soon as you have long index name, you can see them entirely. 
Another quick fix would be to add a "title" to the index links so that before clicking on a link like this one: "a-fairly-long..." we would know on which index we are clicking.

The same request would be interesting on the home page too.

Thanks

Benjamin VADANT for ffly4u

**Comment by xbill82** [comment]
We are going to make it resizable in v4 :point_right: #648
