### ISSUE TITLE
Bugs with collection columns display

### ISSUE THREAD

**Issue by ffly4u** [kuzzleio/kuzzle-admin-console#561]
## Expected Behavior
1. When adding a column, clicking on the dropdown should select the column and allow to add another column.
2. On refreshing the view, the page should display the view!

## Current Behavior
1. Impossible to select anything from the dropdown, I'm getting some errors in the console too when typing in a column name (cf attached file) 
It seems to only happens with highly nested mappings (although selecting a high level field is not working too)
![2019-07-15 17_22_13-DevTools - s3 eu-west-3 amazonaws com_kuzzle-admin-console_index html](https://user-images.githubusercontent.com/46672362/61228177-09694300-a726-11e9-988d-5fb47f1b7853.png)

2. I'm getting a 404 error on refresh

## Steps to Reproduce
1. Go to an index
2. Go to a collection
3. Select column view
4. Try to add a column

## Context (Environment)
Kuzzle version: 1.8.3
Node.js version: 8.16.0
Admin Console Version: 2.5.0

**Comment by xbill82** [comment]
Thank you Benjamin, we've rewritten the column view in v4, so I'll put this issue in the backlog and test the new implementation to see if I reproduce this bug.
