### ISSUE TITLE
Can't edit and delete documents "cannot read property kuzzle_info of undefined"

### ISSUE THREAD

**Issue by Tyki** [kuzzleio/kuzzle-admin-console#569]
When I try to delete or update a document, if the field '_kuzzle_info' is not present, the console can't delete or update a document

## Expected Behavior

Being able to delete or update a document

## Current Behavior

Can't delete or update with a red box showing up saying 'cannot read property kuzzle_info of undefined' 

## Steps to Reproduce

1. Inject a document without _kuzzle_info
2. try to update / delete the document
3.
4.

## Context (Environment)

Kuzzle version: 1.7.6
Node.js version: 8
Admin Console Version: console.kuzzle.io

**Comment by jenow** [comment]
I just tried to put a document inside Kuzzle without any meta data with `curl -X PUT -H 'Content-Type: application/json' http://localhost:9200/issue-569/try/1 -d '{}'` and I am still able to update and delete it. Do you have an error when you are trying to do that?

**Comment by xbill82** [comment]
@Tyki still having this issue?
