### ISSUE TITLE
Dockerfile seems broken

### ISSUE THREAD

**Issue by dbrosy** [kuzzleio/kuzzle-admin-console#600]
clone master branch and run

docker build -t kuzzle-admin-console .

Expect it to build image of kuzzle console, instead it fails on line 5:

COPY ./docker-compose/scripts/run.sh /run.sh

this script no longer exists

normally I would use online version but it seems to be over loaded today.
Plus I will need a stand alone offline solution in future.

can we get regular console images made for hub.docker.com

**Comment by xbill82** [comment]
Hey, thanks for the heads-up, we'll put this in the backlog of the next release!
