### ISSUE TITLE
Display complete roles name in Profile filter

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle-admin-console#658]
When I try to search by roles, they are truncated even if there is still room to display them
![image](https://user-images.githubusercontent.com/4447392/80467971-e61f2580-893e-11ea-8744-ee9878fb9f97.png)

**Comment by xbill82** [comment]
Great feedback! Yes, it would be definitely better to split it in different issues, so that we can use them to organize work in the Projects dashboard and attach the PR directly to each issue.
