### ISSUE TITLE
Display more security results by default 

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle-admin-console#661]
It could be nice to have more results by default with securities or be able to change the page size

IMHO 10 documents is not enough (even for the document view), why we display as little documents?

**Comment by xbill82** [comment]
You can change the page size in the Documents page

![image](https://user-images.githubusercontent.com/5023426/80701421-a8a5ce00-8adf-11ea-8d72-c042d9a8f89e.png)

**Comment by Aschen** [comment]
Sorry when I added this issue it was originally inside the big issue about securities.
I edited the description
