### ISSUE TITLE
Losing custom user content on password update

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle-admin-console#669]
If I have an user with custom content, when I update his credentials I loose the user custom content.

![loosing-user-content](https://user-images.githubusercontent.com/4447392/80476322-8595e580-894a-11ea-8bfb-11cdd6d1e8aa.gif)

**Comment by morgandruesne** [comment]
I can't reproduce this bug, do you have any more information?

![ezgif com-optimize](https://user-images.githubusercontent.com/32675027/80713568-fb898080-8af3-11ea-91c5-0d71cc017f24.gif)
