### ISSUE TITLE
Useless eye icon on indexes list

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle-admin-console#671]
IMHO the eye icon on the index list to open the collection list is useless.

I just figure it out it existed today, most of the time I'm just clicking on the index name

![image](https://user-images.githubusercontent.com/4447392/80560052-e02d5100-89df-11ea-80ff-c6624f9830ad.png)

**Comment by xbill82** [comment]
Interesting, we added it with @Njuelle and @sixla because we thought that clicking on the name of the index wasn't intuitive enough. But I actually agree with you

**Comment by Aschen** [comment]
IMHO we can keep the icon, it's not a big deal and other users may not know that we can click on the index name :+1:

**Comment by xbill82** [comment]
Sure you're right. At the same time... This icon bothers me a bit

**Comment by Njuelle** [comment]
now that you mention it, idk if this button really helps...but it's not a problem to keep it for now I think
