### ISSUE TITLE
Sort by name controls are very far from "Name" label in the index view

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle-admin-console#672]
It's not very easy to guess where the sort by name controls are because they are very far from the actual "Name" label

![image](https://user-images.githubusercontent.com/4447392/80560130-208ccf00-89e0-11ea-8368-9d2f697f0971.png)

**Comment by xbill82** [comment]
Ah, true. Never noticed it. I'm afraid it's rendered by Bootstrap and we'd have to hack the CSS to change it. Let's see if others have the same issue as well.

**Comment by berthieresteban** [comment]
We just need to add the property `sort-icon-left` on the `b-table` to display the icon on the left of the name
https://bootstrap-vue.org/docs/components/table#sort-icon-alignment
