### ISSUE TITLE
Improve CI

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle-admin-console#675]
Travis config should avoid running the CI outside PRs and main branches and it should take into account keywords like `[skip-ci]` and `[wip]`

**Comment by alexandrebouthinon** [comment]
Travis has a built-in feature to skip CI build based on commit message. See https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build
Think about it is not the same as Gitlab CI

**Comment by berthieresteban** [comment]
https://github.com/kuzzleio/kuzzle-admin-console/pull/854#issuecomment-740610956
