### ISSUE TITLE
Advanced search tabs order

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle-admin-console#676]
## Expected Behavior
```gherkin
Given I am on `#/data/testindex/testcollection`
When I click on "Advanced Query" 
Then I see the "Advanced Filter" tab (selected) and, next to it, the "Raw JSON Filter"
```

## Current Behavior
```gherkin
Given I am on `#/data/testindex/testcollection`
When I click on "Advanced Query" 
Then I see the "Raw JSON Filter" tab (selected) and, next to it, the "Advanced Filter"
```

## Possible Solution
... Because @Njuelle and I decided so, but it troubles me now (and @Aschen as well, I think)... Shouldn't we stick to the same tab order as v3.x?

## Context (Environment)
Admin Console Version: v4.x

**Comment by Aschen** [comment]
IMHO most users are not like us and they can't write an ES query by themself

**Comment by xbill82** [comment]
Yes, this morning I had a conversation with a client that totally relies on the Advanced Filter :astonished:

**Comment by xbill82** [comment]
Can we all agree that we should restore the initial order? (cc @Njuelle )
