### ISSUE TITLE
Left tree search for indexes and collections seems broken

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle-admin-console#692]
## Expected Behavior

Being able to search for an index and then unfold it to see the collections inside

## Current Behavior

![left-tree-search](https://user-images.githubusercontent.com/4447392/81245315-f1481480-9014-11ea-904f-0ae94272c7b9.gif)

**Comment by xbill82** [comment]
These are the kind of bugs that make me hate a product
