### ISSUE TITLE
Importing a JSON file for creating default connections results in an error

### ISSUE THREAD

**Issue by Ankhas** [kuzzleio/kuzzle-admin-console#695]
## Expected Behavior
Importing a valid JSON file should create connections in order to connect to a Kuzzle instance.

## Current Behavior
When I try to import a valid JSON file into http://console.kuzzle.io for creating default connections, I got the following errors:

![Screenshot 2020-05-11 at 14 48 06](https://user-images.githubusercontent.com/38790380/81566715-8fccd080-939b-11ea-8af5-ed939d3d96ba.png)

I have 5 connections defined in my JSON file, so I believe there is an error for every connection.
Indeed, I got the same error by testing with only one connection

## Possible Solution
Nico on Kuzzle's Discord seems to find there is a typo issue on a function call

## Steps to Reproduce

1. Create a valid JSON file for creating a connection, example:
```
{
  "prod": {
    "name": "test",
    "color": "#002835",
    "host": "kuzzle.test.com",
    "port": "443",
    "ssl": true
  }
}
```
2. Go to http://console.kuzzle.io/kuzzle-v2/
3. Clear browser cache if there is existing connections already registered
4. Click on the `Import a connection`, then a modal will shows up
5. Click on the `Choose file` button, then select your JSON file
6. Click on the `Import` blue button on the bottom of the modal, you should see the following error message:
```
Error: TypeError: this.$store.direct.dispatch.kuzzle.createEnvurinlent is not a function
``` 

## Context (Environment)

Kuzzle version: 2.X
Node.js version: 12.X
Admin Console Version: 3.2.0

**Comment by xbill82** [comment]
Thanks for the heads-up!
