### ISSUE TITLE
Can't switch collections after token expiration and re authentication

### ISSUE THREAD

**Issue by Njuelle** [kuzzleio/kuzzle-admin-console#733]
## Expected Behavior
when my token expires, and I log back in. I should be able to switch collections/indexes without refreshing the page.

## Current Behavior
after re authentication, when I try to change collections, the router doesn't seem to change the content of the page unless I refresh the page completely.

## Steps to Reproduce
1. login
2. browse a collection
2. wait until token expire
3. log back in
4. try switch collection with the left-bar, nothing happen

## Context (Environment)
Admin Console Version: 4

**Comment by xbill82** [comment]
Nothing in the console?

**Comment by Njuelle** [comment]
fixed by https://github.com/kuzzleio/kuzzle-admin-console/pull/813
