### ISSUE TITLE
Store critical data in IndexedDB rather than localStorage

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle-admin-console#759]
We currently store all the data in the `localStorage`, which is handy but not very secure. We should dig into IndexedDB or other native secure storage solutions at least for critical data like auth tokens.

**Comment by Aschen** [comment]
I'm not sure but I think storing JWT in IndexedDB is as safe as storing them in localStorage since any script running on the page could access IndexedDB

**Comment by xbill82** [comment]
You're probably right. I've read things about localStorage being accessible from any script running on _any other page_ due to security flaws in the model. I'd like to verify this before doing anything about this issue.

**Comment by xbill82** [comment]
Ok, after reading https://owasp.org/www-community/Types_of_Cross-Site_Scripting it looks like this issue is just about evaluating how much the AC (and Kuzzle) is vulnerable to XSS attacks.

**Comment by xbill82** [comment]
Ok, did a quick tour of the codebase and came to the conclusion that we are safe. AFAIK, XSS attacks in Vue are possible whenever we use the `v-html` directive to display user-generated content sent by the server. We use this directive in the `IndexBranch.vue` component that displays index and collection names. However, due to the restrictions that Elasticsearch applies to those names, it is IMHO impossible to use them to inject harmful Javascript in the page.

I'll leave this issue open to gather more thoughts and, if we agree on this conclusion, I'll close it.

(cc @Njuelle and @Aschen )

**Comment by xbill82** [comment]
Update: I made a call with Florens, who seem to agree with my conclusion that stuff looks pretty safe, but he also points some hints to make the app more secure:
* Add a linting rule that prevents future uses of `v-html`
* Explore the ability for Kuzzle to accept auth-token coming from a `http-only` cookie (which will be pretty unlikely to be accepted) so that the token is not accessible in the global JS scope (this would break our environments model, but might be an interesting thought for applications that only connect to a single, hard-coded backend)
* Add a `content-security-policy` in the `index.html` page that would prevent inline JS scripting (this one is the most interesting to me, but might break the dev workflow, as the Webpack agent on the page inlines the diff-chunks coming from the web-server).

**Comment by Aschen** [comment]
>     * Add a `content-security-policy` in the `index.html` page that would prevent inline JS scripting (this one is the most interesting to me, but might break the dev workflow, as the Webpack agent on the page inlines the diff-chunks coming from the web-server).

We could add it only in the final build maybe?

**Comment by xbill82** [comment]
> Also we do not rely on any external script.

But we never audited the NPM libraries BTW

**Comment by Aschen** [comment]
> > Also we do not rely on any external script.
> 
> But we never audited the NPM libraries BTW

That's a very good point. Actually we should be **VERY** careful with external libraries and try to reduce the number of external dependencies from NPM.
