### ISSUE TITLE
Missing visual feedback when user creation form is not complete

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle-admin-console#768]
## Expected Behavior

I expect a visual feedback if I try to create an user without profil

## Current Behavior

The creation does not work and there is no visual feedback about what happen
![missing-visual-feedback](https://user-images.githubusercontent.com/4447392/86081149-f2d20e00-ba94-11ea-8b7d-51578a0cadeb.gif)

## Possible Solution

Adds a red square around the missing inputs

## Steps to Reproduce
1. Start user creation and fill everything but the profile ID
2. Click on create
3.
4.

## Context (Environment)
Admin Console Version: next-console.kuzzle.io

**Comment by xbill82** [comment]
This is a regression: I don't remember exactly what was it but the form did return a visual clue about the inability to create a user without profiles.
