### ISSUE TITLE
No re authenticate form when my token is expired

### ISSUE THREAD

**Issue by Njuelle** [kuzzleio/kuzzle-admin-console#775]
## Expected Behavior
When my token is expired and I try to perform an action, there is modal with the login form who shows up to ask me to re authenticate myself

## Current Behavior
There is only an error toast and an error printed in the console
![image](https://user-images.githubusercontent.com/3192870/86235878-6b21f780-bb99-11ea-814c-0f31c22ef402.png)

## Context (Environment)
Kuzzle version: 2
Admin Console Version: 4.x

**Comment by Njuelle** [comment]
Also, I can't perform the logout action because it's seem to check my token validity for this action

**Comment by Njuelle** [comment]
another point but related to this issue, when my token is expired and go to "Data" page :
![image](https://user-images.githubusercontent.com/3192870/86332924-77668d00-bc4b-11ea-9762-26b58bfc0349.png)

**Comment by xbill82** [comment]
The token expiration is a completely "unexplored" land... We need to do some good work on it. These kind of bugs are quite normal to happen.
