### ISSUE TITLE
Make JSON-form-view great again?

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle-admin-console#790]
The JSON form view might actually not be that useless in the end...

**Comment by xbill82** [comment]
Wow, this actually moved to TO DO with 3 thumbs-up. Ok, let's do it, then.
My stand here is to do it _iiiiincreeeeemeeeeeentaaaaallyyyyyyy_. Like, very very simple in the beginning (1-level depth, no complex fields, fallback to JSON for nested fields) and listen very closely to what the community asks for.
Let's avoid building the bloatware we had in the previous version.

**Comment by m4rrc0** [comment]
A reference implementation of a similar feature for kinto admin is react-jsonschema-form. If that helps...

**Comment by xbill82** [comment]
Thanks a lot @m4rrc0 I'll take a look!

**Comment by xbill82** [comment]
Looks like the equivalent for Vuejs is https://github.com/jarvelov/vue-form-json-schema
