### ISSUE TITLE
Need to improve UX to warn users that an environment is malformed

### ISSUE THREAD

**Issue by Njuelle** [kuzzleio/kuzzle-admin-console#791]
Currently the login page to an environment doesn't seem clear at all, especially when you come from the old Admin Console and still have the old environments backed up in the local storage.

The current behavior is really incomprehensible, the page shows an infinite loader during the connection to Kuzzle that doesn't work. There is an error in the console but nothing is showed on the user side. The only way to know what's going on is to click on the environment selector. 

It should show the info directly on the page in a clearer way.

**Comment by xbill82** [comment]
ok but... what info?

**Comment by xbill82** [comment]
When opening the v4 with an already selected malformed environment, the AC tries to connect to it, the console shows an error, but in the UI we have the infinite loader with no info.

In this case, we should show the update env form with the red error messages.

**Comment by xbill82** [comment]
Fixed.
