### ISSUE TITLE
Can't resize the columns in column view, some data are hidden

### ISSUE THREAD

**Issue by berthieresteban** [kuzzleio/kuzzle-admin-console#799]
Can't resize the columns in column view, some data are hidden

**Comment by berthieresteban** [comment]
Not sure that data are hidden 
The columns width is set to minimal size to allow user see all data contained in cell
The table width is increase by adding columns and allow to scroll horizontally

**Comment by xbill82** [comment]
Yes, I've noticed it. Maybe, we could still keep this feature-request as a "nice-to-have".

**Comment by berthieresteban** [comment]
I found it in `src/components/Data/Documents/Views/Column.vue` line 222, `value: JSON.stringify(ret).substring(0, 10),` 
We display only 10 first char of the string containing the data to display et set `...` next to if we cutted
We did it to prevent for very long strig for example some text fields

**Comment by xbill82** [comment]
oh...
Not good. We should really use the CSS ellipsis rule to adapt the text clipping to the column size.

**Comment by Njuelle** [comment]
set a column maximum width (should be calculated with the window total width) and use `word-wrap` to restrict content size !
