### ISSUE TITLE
Add analytics to the v4

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle-admin-console#804]
We need to get more data-driven about the features we ship on the Admin Console. Te v4 currently lacks the Map and Chart view and the JSON Form view, but people only complain about the JSON Form. This is a good clue that we should implement it first, but it's not precise enough. We're not sure nobody will complain if we ship the v4 to production without the Map and Chart view.

That's why we need an (anonymized) analytics mechanism in the instance of the v4 that we ship on console.kuzzle.io. This module must be built conditionally (we can use the Webpack DefinePlugin to inject an env variable at build time and set it to `true` during the deployment to production).
The analytics module will just report events about which views are opened to an analytics platform.
We need to decide which analytics platform these events will be sent to.
We also need to put an info-box somewhere in the UI to explain the users that this particular instance reports analytics to `<analytics platform here>` and if they want an analytics-free instance, they can clone the repo and host their own.

**Comment by berthieresteban** [comment]
We could let the choice to the user in a banner, he can accept so we get analytics or refuse.

**Comment by berthieresteban** [comment]
Implementation done but no data display on GA
