### ISSUE TITLE
Display the error message in the error toast

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle-admin-console#839]
Actually when an error occur, a generic toast is displayed indicating that the full error has been printed in the console.  

The toast should include Kuzzle error message and print the complete error in the console

**Comment by Njuelle** [comment]
the toast is not really generic, for each error we display a customizable and understandable message, indicating what didn't work

**Comment by Aschen** [comment]
I don't agree because even non-dev people can copy paste the error message and send it to us for example

**Comment by xbill82** [comment]
interesting point... I think that not all error are "pretty-printable" on a toast (the toast is often too small to show them) but the idea of Kuzzle returning human-readable errors that the user can copy-paste to us is nice.

**Comment by Aschen** [comment]
Maybe the toast should be bigger then?

Error messages are not that big: https://docs.kuzzle.io/core/2/api/essentials/error-codes/api/

**Comment by xbill82** [comment]
Yes, I think the toast should definitely be bigger

**Comment by rolljee** [comment]
May it be possible to have a small copy/paste btn?
<img width="237" alt="Screenshot 2020-11-05 at 16 49 14" src="https://user-images.githubusercontent.com/10114634/98263232-ddab4580-1f86-11eb-9247-60b8592f7b9d.png">

So that toast can still remain small and we can get the full error message ?
