### ISSUE TITLE
Table view sorting

### ISSUE THREAD

**Issue by berthieresteban** [kuzzleio/kuzzle-admin-console#844]
## Expected Behavior
Clicking on an arrow of a column in table view should sort the entire document set

# Current Behavior
Clicking on an arrow of a column in table view actually only sort the document of the current selected page

## Possible Solution
  - Could use the built-in pagination option of the b-table component but it'll require to fetch the entire set of documents stored in kuzzle...
  - Could try to catch the sort event of the table and adapt de fetch query for the view and fetch again

## Steps to Reproduce
1. in column view check a collection that has more than 10 documents
2. click on an column header arrow to sort the table
3. only the first page is sorted the the results displayed is errored

**Comment by berthieresteban** [comment]
With last table view (cf: #798) we can't sort anymore so we'll need to implement that feature

**Comment by Njuelle** [comment]
as discussed in backlog refinement, we need to decide if we let the possibility to sort with the advanced search capabilities or if we want to implement the sort in table head => workshop
