### ISSUE TITLE
Prefill raw json filter with query and sort

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle-admin-console#850]
Just trying to use a simple query in the "Raw JSON" tab doesn't works, when clicking on "Search" the documents are not filtered

**Comment by xbill82** [comment]
Do you see an error in the logs or a toast? I used it yesterday and it was working. Can you please post your query here?

**Comment by Aschen** [comment]
Ok my bad, it's because we need to put the query in the `query` property :facepalm: 

Maybe we could prefill the Raw JSON with the `query` and the `sort` properties?

**Comment by xbill82** [comment]
Nice idea! Or simply add a cheatsheet
