### ISSUE TITLE
CreateAt Undefined (invalid date)

### ISSUE THREAD

**Issue by Stan92** [kuzzleio/kuzzle-admin-console#853]
A little bug while adding an object to a collection, the createAt field comes with an undefined (invalid date).
I think it just an issue with the UI (searching the object with postman I get the correct value).

**Comment by berthieresteban** [comment]
I'm closing that issue because Admin Console v4 has been released

**Comment by berthieresteban** [comment]
I'm closing that issue because Admin Console v4 has been released
