### ISSUE TITLE
Display date as YYYY/MM/DD

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle-admin-console#862]
## Description

Actually date are displayed as DD/MM/YYYY HH:MM:SS which can be confusing IMHO.

![image](https://user-images.githubusercontent.com/4447392/102598943-0e050880-411d-11eb-8fc2-5d4bf42db720.png)

Instead we should display it like this: YYYY/MM/DD HH:MM:SS 

So the entire date is from the biggest unit to the smaller unit.

**Comment by xbill82** [comment]
Let's do it, it's an easy and quick win
