### ISSUE TITLE
In user creation, it seems that adding local credentials is mandatory

### ISSUE THREAD

**Issue by berthieresteban** [kuzzleio/kuzzle-admin-console#874]
## Expected Behavior
During user creation, we should be able to add strategies (according to available strategies), or create users without strategies

## Current Behavior
Actually, the UX/UI implicitly requires us to add credentials for local strategy

**Comment by xbill82** [comment]
"create credentials without strategies"? I feel I'm missing something...

**Comment by berthieresteban** [comment]
> "create credentials without strategies"? I feel I'm missing something...
-_- sorry...
"create users without strategies"

**Comment by xbill82** [comment]
ok, feels clearer now...
Ok, why not. Of course you're right, this will need some UX improvements then.
