### ISSUE TITLE
Deadlink for dynamic mapping

### ISSUE THREAD

**Issue by berthieresteban** [kuzzleio/kuzzle-admin-console#875]
link to dynamic mappingsare errored

-> [initial issue](https://github.com/kuzzleio/documentation/issues/517)

**Comment by xbill82** [comment]
That dynamic mapping option should disappear. Dynamic mapping is a per-field option and putting it outside the JSON editor is misleading.

**Comment by berthieresteban** [comment]
I agree, but we should let and fix links no ?

**Comment by xbill82** [comment]
Yes we should, we'll get rid of this later (I fill an issue)
