### ISSUE TITLE
[bug] the search profile action limits the size of the results to 100

### ISSUE THREAD

**Issue by Njuelle** [kuzzleio/kuzzle-admin-console#892]
the `performSearchProfiles` action on the `KuzzleWrapper` service limit the size of the results to 100

https://github.com/kuzzleio/kuzzle-admin-console/blob/4-dev/src/services/kuzzleWrapper-v1.ts#L206

**Comment by Leodau** [comment]
@Njuelle I don't get it, what would be the fix? No limit? Or a bigger/smaller limit?

**Comment by Njuelle** [comment]
@Leodau 
Currently there are Kuzzle users who have more than 100 profiles and when they want to create a new user, they can't access some profiles via the dropdown list. The easiest solution would be to increase the size value.

The most reliable solution would be to redesign the dropdown list to make it a real paginated list, but it will probably require a redesign of the user creation UX

**Comment by xbill82** [comment]
let's increase it to 1000
