### ISSUE TITLE
Admin console not connecting with local kuzzle server in Brave browser

### ISSUE THREAD

**Issue by keval-d** [kuzzleio/kuzzle-admin-console#895]
![Screenshot 2021-01-28 at 2 22 28 PM](https://user-images.githubusercontent.com/68364421/106113274-50862000-6174-11eb-986b-909133e11752.png)

Admin console not connecting with local kuzzle server in brave browser but live server admin console is working

## Context (Environment)
Kuzzle version: 2.9.1
Node.js version: v15.7.0
npm version: 7.4.3
Admin Console Version: 3.2.0
OS & version: macOS Catalina 10.15.7
Brave Browser version:  1.19.86 Chromium: 88.0.4324.96 (Official Build) (x86_64)

**Comment by xbill82** [comment]
Hey, thanks for the heads-up. We have never tested the Admin Console in the Brave Browser. It seems to me the problem comes from the Kuzzle Javascript SDK. Did you ever run any application using the SDK in the Brave Browser? We'll also run our own tests.

**Comment by keval-d** [comment]
You need to do shield down for that site. It will work.

**Comment by xbill82** [comment]
Ok, "shield down" seems to be a feature of Brave browser isn't it? Should we close this issue?
