### ISSUE TITLE
Next-Console

### ISSUE THREAD

**Issue by expandboard** [kuzzleio/kuzzle-admin-console#897]
Where can i find next-console version repository of kuzzle admin console? this is old version.

**Comment by Njuelle** [comment]
Hi @expandboard,
next-console.kuzzle.io is the version used by the team to deploy the new features still in beta, so it is ahead of console.kuzzle.io.

You must use the [`4-dev` branch](https://github.com/kuzzleio/kuzzle-admin-console/tree/4-dev) of the repository to use the next version.

**Comment by expandboard** [comment]
Hi @Njuelle, 
Thanks for your great job
