### ISSUE TITLE
[bug] Correctly update the quick-search input

### ISSUE THREAD

**Issue by Leodau** [kuzzleio/kuzzle-admin-console#908]
## Expected Behavior
Correctly have quick-search in sync with the interface.

## Current Behavior
When changing pages **after** doing a search and coming back, the query is saved and applied BUT the search input is empty.
(Ghost query effect)

_It seems like the search queries are correctly saved and re-applied on page refresh, but the search input control is not in sync._

## Steps to Reproduce
1. Go to the Security/User tab.
2. Create a new user (_kuid_ test)
3. Back at the User tab, execute a quick-search like: `alyx` _(You should now have an empty result)_
4. Click and go to another tab (_ex. Profiles)_
5. Click and come back to the User tab. _(You should see that your **input** is empty, but your query is still being applied)_

Or,
1. Make any quick-search query
2. Reload the page

## Context (Environment)
Kuzzle version: 2.9.2
Admin Console version: 4

**Comment by xbill82** [comment]
Let's take a moment to solve the problem of the AutoFocus
