### ISSUE TITLE
Add a custom Geo-point form-view input in the document create/update form

### ISSUE THREAD

**Issue by Njuelle** [kuzzleio/kuzzle-admin-console#912]
## Feature Description
Add a custom vue-form-generator Geo-point input

Actually, in the form view, geo-points are displayed with a JSON-input. It is necessary to create a new custom input. this one will have to instantiate a map, centered on the geo-point. Clicking on the map will redefine the new geo-point.

* custom input exemple : https://github.com/kuzzleio/kuzzle-admin-console/blob/master/src/components/Data/Documents/FormInputs/JsonFormInput.vue

* component should be register here : https://github.com/kuzzleio/kuzzle-admin-console/blob/master/src/main.ts#L32
* update the form schema service : https://github.com/kuzzleio/kuzzle-admin-console/blob/master/src/services/formSchema.ts

**Comment by xbill82** [comment]
Please add "in the document create/update form" in the title
