### ISSUE TITLE
Add a feedback form

### ISSUE THREAD

**Issue by Njuelle** [kuzzleio/kuzzle-admin-console#913]
## Feature Description
We need to collect feedback about the features implemented in the Admin-console.

### Possible solution
Rating with 5 stars on  admin console pages

Also a form with simple text?

**Comment by xbill82** [comment]
Looks like a useful thing. I suggest we create some sort of dropdown menu, right upon the Kuzzle logo on the top left corner, which would contain
* info (build number, version, kuzzle version)
* contribute link (github issues) 👉  #902 
* send us feedback (opens a modal with a form: stars and comments: sends this to..?)

**Comment by berthieresteban** [comment]
I created a PR with a dropdown for feedback on github, stackoverflow and discord
I think we shouldn't add another feedback form because we already have lot of communication channels
