### ISSUE TITLE
Table doesn't display all of the items when changing numbers of items per page

### ISSUE THREAD

**Issue by jsatge** [kuzzleio/kuzzle-admin-console#917]
## Expected Behavior
List all the items in the table.

## Current Behavior
When we are on a page that is not the first and we change the number of items to display per page it's not displaying all the items but only those on this page and on the pages after.

![Capture d’écran du 2021-04-16 12-08-59](https://user-images.githubusercontent.com/62239716/115010847-2f4cea00-9eae-11eb-8e80-88dab511ef04.png)

## Steps to Reproduce
1. Go on the last page of a table
2. Change the numbers of items per page

**Comment by xbill82** [comment]
Do you see weird errors on the console when switching the number of items per page?

**Comment by jsatge** [comment]
> Do you see weird errors on the console when switching the number of items per page?

I don't see anything in the console.
