### ISSUE TITLE
Unable to logout if token is invalid

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle-admin-console#955]
If the token is invalid (which happens if you restart your backend) the logout action fails and the login page is never displayed until the page is refreshed.

**Comment by jsatge** [comment]
I tested the logout like this:

- Run a Kuzzle
- Log in AC
- Kill and restart a Kuzzle
- Logout

And everything is working for me. What is the way to have this bug ?

**Comment by berthieresteban** [comment]
I'm able to reproduce, just stop your backend without restarting it, you won't be able to logout so you won't be able to change env nor user

**Comment by jsatge** [comment]
Isn't it a normal behavior if the backend is not running anymore ?

**Comment by berthieresteban** [comment]
Well since it stuck you in the current environment on which you can't do anything I don't think so
It might be another issue but IMHO we should be able to get back to the environment selector
We probably need more info here @xbill82

**Comment by xbill82** [comment]
Well... Technically, @jsatge is not wrong: it makes no sense to end a session against a backend that is not responding. But, try deleting the token from Redis directly. The `logout` action is rejected because the token is not valid so... no logout nor login form is shown. The aim is to allow the user "just get out of here", so let's make the `logout` function a little bit more resilient.
