### ISSUE TITLE
telemetry bug ?

### ISSUE THREAD

**Issue by LouisAxelViala** [kuzzleio/kuzzle-admin-console#990]
When i replace or update a JSON doc i have a pop up message hich lasts less than a second i can't screen and in the console i have a specific message. The modification has been saved but the message is still there.
## Expected Behavior

I save the doc and no error should pop

## Current Behavior

pop error message and error in the console in UTA and PROD back

## Steps to Reproduce

1. Admin account
2. index of one customer
3. config for exemple
4. modify smthing
5. replace or update
6. See the pop error message

## Context (Environment)

Kuzzle version:
Node.js version:
Admin Console version:

**Comment by Aschen** [comment]
@LouisAxelViala I sent you a message on the private customer chat
